#smtp
smtp:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-app-password
  from: noreply@yourdomain.com

#db config
database:
  uri: mongodb://alta_user:your_database_password@localhost:27017/