#smtp
smtp:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-app-password
  from: noreply@yourdomain.com

#db config
database:
  uri: mongodb://localhost:27017
  name: altacore
  username:
  password:

# Website configuration
website:
  url: http://localhost:3000